In [1]:
import torch
import numpy as np

In [2]:
print(torch.__version__)

1.6.0


In [3]:
torch.cuda.is_available()

True

In [4]:
torch.version.cuda

'10.2'

In [5]:
torch.cuda.get_device_name(0)

'Quadro P6000'

### Using CUDA

In [6]:
t=torch.tensor([1,2,3])
t

tensor([1, 2, 3])

In [7]:
t=t.cuda()
t

tensor([1, 2, 3], device='cuda:0')

### Tensors

In [8]:
a=[1,2,3,4]

In [9]:
a[2]

3

In [10]:
dd=[
    [1,2,3],
    [4,5,6],
    [7,8,9]
]

In [11]:
dd[0]

[1, 2, 3]

In [12]:
dd[1]

[4, 5, 6]

In [13]:
dd[2]

[7, 8, 9]

In [14]:
dd[0][0]

1

In [15]:
dd[0][1]

2

In [16]:
dd[0][2]

3

In [17]:
t=torch.tensor(dd)
t

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [18]:
type(t)

torch.Tensor

In [19]:
t.shape

torch.Size([3, 3])

In [20]:
t.reshape(1,9)

tensor([[1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [21]:
t.reshape(1,9).shape

torch.Size([1, 9])

In [22]:
t=torch.Tensor()
type(t)

torch.Tensor

In [23]:
print(t.dtype)
print(t.device)
print(t.layout)

torch.float32
cpu
torch.strided


In [24]:
device=torch.device("cuda:0")
device

device(type='cuda', index=0)

In [25]:
t1=torch.tensor([1,2,3])
t2=torch.tensor([1.,2.,3.])

In [26]:
t1.dtype

torch.int64

In [27]:
t2.dtype

torch.float32

In [28]:
t1+t2

tensor([2., 4., 6.])

In [29]:
t1=torch.tensor([1,2,3])
t2=t1.cuda()

In [30]:
t1.device

device(type='cpu')

In [31]:
t2.device

device(type='cuda', index=0)

In [32]:
t1+t2

RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cuda:0 and cpu!

In [33]:
torch.eye(2)

tensor([[1., 0.],
        [0., 1.]])

In [34]:
torch.zeros(2,2)

tensor([[0., 0.],
        [0., 0.]])

In [35]:
torch.ones(2,2)

tensor([[1., 1.],
        [1., 1.]])

In [36]:
torch.rand(2,2)

tensor([[0.0167, 0.6180],
        [0.7823, 0.3673]])

In [37]:
data=np.array([1,2,3])
type(data)

numpy.ndarray

In [38]:
t1=torch.Tensor(data)

In [39]:
t2=torch.tensor(data)

In [40]:
t3=torch.as_tensor(data)

In [41]:
t4=torch.from_numpy(data)

In [42]:
print(t1)
print(t2)
print(t3)
print(t4)

tensor([1., 2., 3.])
tensor([1, 2, 3])
tensor([1, 2, 3])
tensor([1, 2, 3])


In [43]:
print(t1.dtype)
print(t2.dtype)
print(t3.dtype)
print(t4.dtype)

torch.float32
torch.int64
torch.int64
torch.int64


In [44]:
torch.get_default_dtype()

torch.float32

#### Sharing Memory

In [45]:
data[0]=0

In [46]:
print(t1)
print(t2)
print(t3)
print(t4)

tensor([1., 2., 3.])
tensor([1, 2, 3])
tensor([0, 2, 3])
tensor([0, 2, 3])


In [47]:
t1[0]=9

In [48]:
print(t1)
print(t2)
print(t3)
print(t4)

tensor([9., 2., 3.])
tensor([1, 2, 3])
tensor([0, 2, 3])
tensor([0, 2, 3])


In [49]:
t3[0]=6

In [50]:
print(t1)
print(t2)
print(t3)
print(t4)

tensor([9., 2., 3.])
tensor([1, 2, 3])
tensor([6, 2, 3])
tensor([6, 2, 3])


### Reshaping Tensors

In [51]:
t=torch.tensor([[1,1,1,1],
                [2,2,2,2],
                [3,3,3,3]],dtype=torch.float32)

In [52]:
t.size()

torch.Size([3, 4])

In [53]:
t.shape

torch.Size([3, 4])

In [54]:
len(t.shape)

2

In [55]:
torch.tensor(t.shape).prod()

tensor(12)

In [56]:
t.numel()

12

#### Reshape-keeping rank=2

In [57]:
t.reshape([1,12])

tensor([[1., 1., 1., 1., 2., 2., 2., 2., 3., 3., 3., 3.]])

In [58]:
t.reshape(12,1)

tensor([[1.],
        [1.],
        [1.],
        [1.],
        [2.],
        [2.],
        [2.],
        [2.],
        [3.],
        [3.],
        [3.],
        [3.]])

In [59]:
t.reshape([2,6])

tensor([[1., 1., 1., 1., 2., 2.],
        [2., 2., 3., 3., 3., 3.]])

In [60]:
t.reshape(2,6)

tensor([[1., 1., 1., 1., 2., 2.],
        [2., 2., 3., 3., 3., 3.]])

In [61]:
t.reshape(6,2)

tensor([[1., 1.],
        [1., 1.],
        [2., 2.],
        [2., 2.],
        [3., 3.],
        [3., 3.]])

In [62]:
t.reshape([3,4])

tensor([[1., 1., 1., 1.],
        [2., 2., 2., 2.],
        [3., 3., 3., 3.]])

In [63]:
t.reshape([4,3])

tensor([[1., 1., 1.],
        [1., 2., 2.],
        [2., 2., 3.],
        [3., 3., 3.]])

#### Reshape-keeping rank=3

In [64]:
t.reshape([2,2,3])

tensor([[[1., 1., 1.],
         [1., 2., 2.]],

        [[2., 2., 3.],
         [3., 3., 3.]]])

#### Squeezing and Unsqueezing

In [65]:
print(t.reshape([1,12]))
print(t.reshape([1,12]).shape)

tensor([[1., 1., 1., 1., 2., 2., 2., 2., 3., 3., 3., 3.]])
torch.Size([1, 12])


In [66]:
print(t.reshape([1,12]).squeeze())
print(t.reshape([1,12]).squeeze().shape)

tensor([1., 1., 1., 1., 2., 2., 2., 2., 3., 3., 3., 3.])
torch.Size([12])


In [67]:
print(t.reshape([1,12]).squeeze().unsqueeze(dim=0))
print(t.reshape([1,12]).squeeze().unsqueeze(dim=0).shape)

tensor([[1., 1., 1., 1., 2., 2., 2., 2., 3., 3., 3., 3.]])
torch.Size([1, 12])


In [68]:
print(t.reshape([2,2,3]))
print(t.reshape([2,2,3]).shape)

tensor([[[1., 1., 1.],
         [1., 2., 2.]],

        [[2., 2., 3.],
         [3., 3., 3.]]])
torch.Size([2, 2, 3])


In [69]:
print(t.reshape([2,2,3]).squeeze())
print(t.reshape([2,2,3]).squeeze().shape)

tensor([[[1., 1., 1.],
         [1., 2., 2.]],

        [[2., 2., 3.],
         [3., 3., 3.]]])
torch.Size([2, 2, 3])


In [70]:
print(t.reshape([2,2,3]).squeeze().unsqueeze(dim=0))
print(t.reshape([2,2,3]).squeeze().unsqueeze(dim=0).shape)

tensor([[[[1., 1., 1.],
          [1., 2., 2.]],

         [[2., 2., 3.],
          [3., 3., 3.]]]])
torch.Size([1, 2, 2, 3])


#### Flatten - 
create a 1d tensor from a nd tendor

In [71]:
def flatten(t):
    t=t.reshape(1,-1)
    t=t.squeeze()
    return t

In [72]:
flatten(t)   #reshape and squeeze(flatten)

tensor([1., 1., 1., 1., 2., 2., 2., 2., 3., 3., 3., 3.])

In [73]:
t.reshape(1,12)  #reshape only

tensor([[1., 1., 1., 1., 2., 2., 2., 2., 3., 3., 3., 3.]])

In [74]:
t.reshape(1,12)[0]    #flatten operation using only reshape

tensor([1., 1., 1., 1., 2., 2., 2., 2., 3., 3., 3., 3.])

In [75]:
t.reshape([1,12]).shape

torch.Size([1, 12])

In [76]:
t.reshape([1,12]).shape[0]

1

In [77]:
t.reshape([t.reshape([1,12]).shape[0],t.reshape([1,12]).shape[1]])[0]

tensor([1., 1., 1., 1., 2., 2., 2., 2., 3., 3., 3., 3.])

In [78]:
t.reshape(1,-1).squeeze()

tensor([1., 1., 1., 1., 2., 2., 2., 2., 3., 3., 3., 3.])

In [79]:
t=torch.ones(4,3)
t

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])

In [80]:
flatten(t)

tensor([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

#### Ci=oncatenating Tensors

In [81]:
t1=torch.tensor([[1,2],[3,4]])
t2=torch.tensor([[5,6],[7,8]])

In [82]:
torch.cat((t1,t2),dim=0)

tensor([[1, 2],
        [3, 4],
        [5, 6],
        [7, 8]])

In [83]:
torch.cat((t1,t2),dim=1)

tensor([[1, 2, 5, 6],
        [3, 4, 7, 8]])

In [84]:
torch.cat((t1,t2),dim=0).shape

torch.Size([4, 2])

In [85]:
torch.cat((t1,t2),dim=1).shape

torch.Size([2, 4])

### CNN Flatten Operation

In [86]:
t1=torch.tensor([[1,1,1,1],
                [1,1,1,1],
                [1,1,1,1],
                [1,1,1,1]])

t2=torch.tensor([[2,2,2,2],
                [2,2,2,2],
                [2,2,2,2],
                [2,2,2,2]])

t3=torch.tensor([[3,3,3,3],
                [3,3,3,3],
                [3,3,3,3],
                [3,3,3,3]])

In [87]:
t=torch.stack((t1,t2,t3))
t.shape

torch.Size([3, 4, 4])

In [88]:
t

tensor([[[1, 1, 1, 1],
         [1, 1, 1, 1],
         [1, 1, 1, 1],
         [1, 1, 1, 1]],

        [[2, 2, 2, 2],
         [2, 2, 2, 2],
         [2, 2, 2, 2],
         [2, 2, 2, 2]],

        [[3, 3, 3, 3],
         [3, 3, 3, 3],
         [3, 3, 3, 3],
         [3, 3, 3, 3]]])

In [89]:
t.reshape(3,1,4,4)

tensor([[[[1, 1, 1, 1],
          [1, 1, 1, 1],
          [1, 1, 1, 1],
          [1, 1, 1, 1]]],


        [[[2, 2, 2, 2],
          [2, 2, 2, 2],
          [2, 2, 2, 2],
          [2, 2, 2, 2]]],


        [[[3, 3, 3, 3],
          [3, 3, 3, 3],
          [3, 3, 3, 3],
          [3, 3, 3, 3]]]])

#### Flattening the Tensor Batch

In [90]:
t.reshape(1,-1)[0]

tensor([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2,
        2, 2, 2, 2, 2, 2, 2, 2, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3])

In [91]:
t.reshape(-1)

tensor([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2,
        2, 2, 2, 2, 2, 2, 2, 2, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3])

In [92]:
t.view(t.numel())

tensor([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2,
        2, 2, 2, 2, 2, 2, 2, 2, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3])

In [93]:
t.flatten()

tensor([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2,
        2, 2, 2, 2, 2, 2, 2, 2, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3])

#### Flattening Specific Axes Of A Tensor

In [94]:
t.flatten(start_dim=0)  #0=Batch axis

tensor([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2,
        2, 2, 2, 2, 2, 2, 2, 2, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3])

In [95]:
t.flatten(start_dim=1)  #1=colour axis

tensor([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
        [2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2],
        [3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3]])

In [96]:
t.flatten(start_dim=2)  #2=height axis

tensor([[[1, 1, 1, 1],
         [1, 1, 1, 1],
         [1, 1, 1, 1],
         [1, 1, 1, 1]],

        [[2, 2, 2, 2],
         [2, 2, 2, 2],
         [2, 2, 2, 2],
         [2, 2, 2, 2]],

        [[3, 3, 3, 3],
         [3, 3, 3, 3],
         [3, 3, 3, 3],
         [3, 3, 3, 3]]])

In [97]:
t.flatten(start_dim=1).shape 

torch.Size([3, 16])

In [98]:
t.reshape(3,-1)   #flatten using reshape only

tensor([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
        [2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2],
        [3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3]])

#### Flattening An RGB Image

In [99]:
r=torch.ones(1,2,2)
g=torch.ones(1,2,2)+1
b=torch.ones(1,2,2)+2
img=torch.cat((r,g,b),dim=0)
img

tensor([[[1., 1.],
         [1., 1.]],

        [[2., 2.],
         [2., 2.]],

        [[3., 3.],
         [3., 3.]]])

In [100]:
img.shape

torch.Size([3, 2, 2])

In [101]:
img.flatten(start_dim=0)

tensor([1., 1., 1., 1., 2., 2., 2., 2., 3., 3., 3., 3.])

In [102]:
img.flatten(start_dim=1)

tensor([[1., 1., 1., 1.],
        [2., 2., 2., 2.],
        [3., 3., 3., 3.]])

In [103]:
img.flatten(start_dim=2)

tensor([[[1., 1.],
         [1., 1.]],

        [[2., 2.],
         [2., 2.]],

        [[3., 3.],
         [3., 3.]]])

### Element wise Tensor operations 

In [104]:
t1=torch.tensor([[1,2],[3,4]],dtype=torch.float32)
t2=torch.tensor([[9,8],[7,6]],dtype=torch.float32)    

In [105]:
t1[0]    #element from first axis

tensor([1., 2.])

In [106]:
t1[0][0]  #element from second axis

tensor(1.)

In [107]:
t2[0][0]

tensor(9.)

In [108]:
t1+t2

tensor([[10., 10.],
        [10., 10.]])

In [109]:
t1+2

tensor([[3., 4.],
        [5., 6.]])

In [110]:
t1-2

tensor([[-1.,  0.],
        [ 1.,  2.]])

In [111]:
t1*2

tensor([[2., 4.],
        [6., 8.]])

In [112]:
t1/2

tensor([[0.5000, 1.0000],
        [1.5000, 2.0000]])

In [113]:
t1.add(2)

tensor([[3., 4.],
        [5., 6.]])

In [114]:
t1.sub(2)

tensor([[-1.,  0.],
        [ 1.,  2.]])

In [115]:
t1.mul(2)

tensor([[2., 4.],
        [6., 8.]])

In [116]:
t1.div(2)

tensor([[0.5000, 1.0000],
        [1.5000, 2.0000]])

In [117]:
np.broadcast_to(2,t1.shape)

array([[2, 2],
       [2, 2]])

In [118]:
t1+2

tensor([[3., 4.],
        [5., 6.]])

In [119]:
t1+torch.tensor(np.broadcast_to(2,t1.shape),dtype=torch.float32)

<ipython-input-119-05f758dab8d3>:1: UserWarning: The given NumPy array is not writeable, and PyTorch does not support non-writeable tensors. This means you can write to the underlying (supposedly non-writeable) NumPy array using the tensor. You may want to copy the array to protect its data or make it writeable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at  /opt/conda/conda-bld/pytorch_1595629395347/work/torch/csrc/utils/tensor_numpy.cpp:141.)
  t1+torch.tensor(np.broadcast_to(2,t1.shape),dtype=torch.float32)


tensor([[3., 4.],
        [5., 6.]])

In [120]:
# Adding tensors of different shapes using broadcasting
t1=torch.tensor([[1,1],[1,1]],dtype=torch.float32)
t2=torch.tensor([2,4],dtype=torch.float32)

In [121]:
t1+t2

tensor([[3., 5.],
        [3., 5.]])

In [122]:
np.broadcast_to(t2.numpy(),t1.shape)

array([[2., 4.],
       [2., 4.]], dtype=float32)

#### Elementwise Comparison

In [123]:
t=torch.tensor([[0,5,0],
                [6,0,7],
                [0,8,0]],
                dtype=torch.float32)

In [124]:
t.eq(0)  #equals to 0

tensor([[ True, False,  True],
        [False,  True, False],
        [ True, False,  True]])

In [125]:
t.ge(0)  #greater than or equal to 0

tensor([[True, True, True],
        [True, True, True],
        [True, True, True]])

In [126]:
t.gt(0)  #greater than 0

tensor([[False,  True, False],
        [ True, False,  True],
        [False,  True, False]])

In [127]:
t.lt(0)   #lower than 0

tensor([[False, False, False],
        [False, False, False],
        [False, False, False]])

In [128]:
t.le(7)   #less than or equal to 7

tensor([[ True,  True,  True],
        [ True,  True,  True],
        [ True, False,  True]])

In [129]:
# Using Broadcasting
t <=torch.tensor(np.broadcast_to(7,t.shape),dtype=torch.float32)

tensor([[ True,  True,  True],
        [ True,  True,  True],
        [ True, False,  True]])

In [130]:
t<=torch.tensor([[7,7,7],
                 [7,7,7],
                 [7,7,7]],
                 dtype=torch.float32)

tensor([[ True,  True,  True],
        [ True,  True,  True],
        [ True, False,  True]])

#### Element-Wise Operations Using Functions

In [131]:
t.abs()

tensor([[0., 5., 0.],
        [6., 0., 7.],
        [0., 8., 0.]])

In [132]:
t.sqrt()

tensor([[0.0000, 2.2361, 0.0000],
        [2.4495, 0.0000, 2.6458],
        [0.0000, 2.8284, 0.0000]])

In [133]:
t.neg()

tensor([[-0., -5., -0.],
        [-6., -0., -7.],
        [-0., -8., -0.]])

In [134]:
t.neg().abs()

tensor([[0., 5., 0.],
        [6., 0., 7.],
        [0., 8., 0.]])

### Reduction Operations on Tensors

In [135]:
t=torch.tensor([[0,1,0],
                [2,0,2],
                [0,3,0]],
                dtype=torch.float32)

In [136]:
t.sum()

tensor(8.)

In [137]:
t.numel()

9

In [138]:
t.sum().numel()

1

#### Reducing Tensors By Axes

In [139]:
t=torch.tensor([[1,1,1,1],
                [2,2,2,2],
                [3,3,3,3]],
                dtype=torch.float32)

In [140]:
t.sum(dim=0)

tensor([6., 6., 6., 6.])

In [141]:
t[0]

tensor([1., 1., 1., 1.])

In [142]:
t[1]

tensor([2., 2., 2., 2.])

In [143]:
t[2]

tensor([3., 3., 3., 3.])

In [144]:
t[0]+t[1]+t[2]

tensor([6., 6., 6., 6.])

In [145]:
t.sum(dim=1)

tensor([ 4.,  8., 12.])

In [146]:
t[0].sum()

tensor(4.)

In [147]:
t[1].sum()

tensor(8.)

In [148]:
t[2].sum()

tensor(12.)

#### Argmax Tensor Reduction Operation


In [149]:
t=torch.tensor([[1,0,0,2],
                [0,3,3,0],
                [4,0,0,5]],
                dtype=torch.float32)

In [150]:
t.max()

tensor(5.)

In [151]:
t.argmax()

tensor(11)

In [152]:
t.flatten()

tensor([1., 0., 0., 2., 0., 3., 3., 0., 4., 0., 0., 5.])

In [154]:
t.max(dim=0)

torch.return_types.max(
values=tensor([4., 3., 3., 5.]),
indices=tensor([2, 1, 1, 2]))

In [155]:
t.argmax(dim=0)

tensor([2, 1, 1, 2])

In [156]:
t.max(dim=1)

torch.return_types.max(
values=tensor([2., 3., 5.]),
indices=tensor([3, 1, 3]))

In [157]:
t.argmax(dim=1)

tensor([3, 2, 3])

#### Accessing Elements Inside Tensors

In [160]:
t=torch.tensor([[1,2,3],
                [4,5,6],
                [7,8,9]],
                dtype=torch.float32)

In [161]:
t.mean()

tensor(5.)

In [162]:
t.mean().item()

5.0

In [163]:
t.mean(dim=0).tolist()

[4.0, 5.0, 6.0]

In [164]:
t.mean(dim=0).numpy()

array([4., 5., 6.], dtype=float32)