In [1]:
import torch
import numpy as np

In [2]:
print(torch.__version__)

1.6.0


In [3]:
torch.cuda.is_available()

True

In [4]:
torch.version.cuda

'10.2'

In [5]:
torch.cuda.get_device_name(0)

'Quadro P5000'

### Using CUDA

In [6]:
t=torch.tensor([1,2,3])
t

tensor([1, 2, 3])

In [7]:
t=t.cuda()
t

tensor([1, 2, 3], device='cuda:0')

### Tensors

In [8]:
a=[1,2,3,4]

In [9]:
a[2]

3

In [10]:
dd=[
    [1,2,3],
    [4,5,6],
    [7,8,9]
]

In [11]:
dd[0]

[1, 2, 3]

In [12]:
dd[1]

[4, 5, 6]

In [13]:
dd[2]

[7, 8, 9]

In [14]:
dd[0][0]

1

In [15]:
dd[0][1]

2

In [16]:
dd[0][2]

3

In [17]:
t=torch.tensor(dd)
t

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [18]:
type(t)

torch.Tensor

In [19]:
t.shape

torch.Size([3, 3])

In [20]:
t.reshape(1,9)

tensor([[1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [21]:
t.reshape(1,9).shape

torch.Size([1, 9])

In [23]:
t=torch.Tensor()
type(t)

torch.Tensor

In [24]:
print(t.dtype)
print(t.device)
print(t.layout)

torch.float32
cpu
torch.strided


In [25]:
device=torch.device("cuda:0")
device

device(type='cuda', index=0)

In [26]:
t1=torch.tensor([1,2,3])
t2=torch.tensor([1.,2.,3.])

In [27]:
t1.dtype

torch.int64

In [28]:
t2.dtype

torch.float32

In [29]:
t1+t2

tensor([2., 4., 6.])

In [30]:
t1=torch.tensor([1,2,3])
t2=t1.cuda()

In [32]:
t1.device

device(type='cpu')

In [33]:
t2.device

device(type='cuda', index=0)

In [34]:
t1+t2

RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cuda:0 and cpu!

In [35]:
data=np.array([1,2,3])
type(data)

numpy.ndarray

In [36]:
torch.Tensor(data)

tensor([1., 2., 3.])

In [37]:
torch.tensor(data)

tensor([1, 2, 3])

In [38]:
torch.as_tensor(data)

tensor([1, 2, 3])

In [39]:
torch.from_numpy(data)

tensor([1, 2, 3])

In [40]:
torch.eye(2)

tensor([[1., 0.],
        [0., 1.]])

In [41]:
torch.zeros(2,2)

tensor([[0., 0.],
        [0., 0.]])

In [42]:
torch.ones(2,2)

tensor([[1., 1.],
        [1., 1.]])

In [43]:
torch.rand(2,2)

tensor([[0.8809, 0.2321],
        [0.8411, 0.2878]])