## 1

In [13]:
import torch     #arrays for Array math (similar to numpy) on GPU

In [3]:
x = torch.Tensor([5,3])
y = torch.Tensor([2,1])

print(x*y)

tensor([10.,  3.])


In [4]:
x = torch.zeros([2,5])
print(x)

tensor([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]])


In [6]:
x.shape

torch.Size([2, 5])

In [7]:
y = torch.rand([2,5])
print(y)

tensor([[0.1396, 0.0501, 0.2484, 0.9725, 0.4856],
        [0.0112, 0.0263, 0.5705, 0.4670, 0.6442]])


In [12]:
y.view([1,10])   #view is same as reshape in numpy and tensorflow

tensor([[0.1396, 0.0501, 0.2484, 0.9725, 0.4856, 0.0112, 0.0263, 0.5705, 0.4670,
         0.6442]])

In [9]:
y

tensor([[0.1396, 0.0501, 0.2484, 0.9725, 0.4856],
        [0.0112, 0.0263, 0.5705, 0.4670, 0.6442]])

In [11]:
y = y.view([1,10])
y

tensor([[0.1396, 0.0501, 0.2484, 0.9725, 0.4856, 0.0112, 0.0263, 0.5705, 0.4670,
         0.6442]])